###
GET http://localhost:8080/api/cities

###
POST http://localhost:8080/api/cities
Content-Type: application/json

{"name": "Ryazan"}

###
GET http://localhost:8080/api/cities/all/Tomsk

###
GET http://localhost:8080/api/cities/aa0c4adc-2195-4ccf-bc33-aeca2cea6f7b

###
PUT http://localhost:8080/api/cities/aa0c4adc-2195-4ccf-bc33-aeca2cea6f7b
Content-Type: application/json

{"name":  "Tmsk"}

###
DELETE http://localhost:8080/api/cities/aa0c4adc-2195-4ccf-bc33-aeca2cea6f7b

###
GET http://localhost:8080/api/weather/7b6815c3-31a2-4bde-a131-efe315b46529

###
POST http://localhost:8080/api/weather/
Content-Type: application/json

{
  "cityId": "7b6815c3-31a2-4bde-a131-efe315b46529",
  "dateTime": "2023-10-15 19:30:00",
  "temperature": 13.50,
  "weatherTypeId": 1006
}

###
PUT http://localhost:8080/api/weather/
Content-Type: application/json

{"weatherObservationId": "9d913ede-e394-4e7e-a123-6e16b8ed4936", "temperature": 13.25, "weatherTypeId": 1003}

###
DELETE http://localhost:8080/api/weather/observations/9d913ede-e394-4e7e-a123-6e16b8ed4936

###
GET http://localhost:8080/api/weather-types

###
PUT http://localhost:8080/api/weather-types
Content-Type: application/json

{"id":  1000, "dayDescription":  "Sunny, init?", "nightDescription":  "Where is the sun, eh?"}

###
GET http://localhost:8080/api/weather-types/1000

###
DELETE http://localhost:8080/api/weather-types/1000

